win-linux/package/windows/common.iss
win-linux/src/linux/cmainwindow.cpp
win-linux/src/win/mainwindow.cpp

merge develop to master after release version 4.8.7

release 4.8.7

---

Makefile

Add platformthemes to desktopeditors folder

Fix qt distribution issue

---

common/loginpage/src/locale.js

added translations for the autocheck for updates option (de, fr, it, ru)

---

common/loginpage/src/locale.js

Updated translations (fr, de)

---

common/loginpage/src/locale.js
macos/Localization/de.xliff
macos/Localization/es.xliff
macos/Localization/fr.xliff
macos/Localization/it.xliff
macos/Localization/pt-BR.xliff

Added translations - de, es, fr, it, pt-br

---

common/loginpage/src/locale.js

Added translations for Interface theme

Added translations (Interface theme - en, ru, de, it, fr, es, pt)

---

common/loginpage/src/locale.js

changed the order of words in translations (ru, es, fr, pt)

fix bug 50470

---

macos/Localization/en.xliff

Fix bug 52577

---

macos/Localization/bg.xliff
macos/Localization/de.xliff
macos/Localization/el.xliff
macos/Localization/es.xliff
macos/Localization/fi.xliff
macos/Localization/fr.xliff
macos/Localization/ga.xliff
macos/Localization/hi.xliff
macos/Localization/hr.xliff
macos/Localization/hu.xliff
macos/Localization/id.xliff
macos/Localization/it.xliff
macos/Localization/lo.xliff
macos/Localization/lv.xliff
macos/Localization/nn.xliff
macos/Localization/pl.xliff
macos/Localization/pt-BR.xliff
macos/Localization/ru.xliff
macos/Localization/sk.xliff
macos/Localization/sl.xliff
macos/Localization/sv.xliff
macos/Localization/tr.xliff
macos/Localization/uk.xliff
macos/Localization/zh-Hans-CN.xliff

add new lines, edit translations

---

win-linux/langs/cs.ts
win-linux/langs/nl.ts
win-linux/langs/pt_BR.ts
win-linux/package/windows/uninstall_page.iss

edit - .ts (nl, cs, pt_BR), add - Uninstall (pt_BR)

add cs, nl, pt (formats description)

---

win-linux/defaults.pri
win-linux/src/components/cfiledialog.cpp
win-linux/src/platform_linux/kdefiledialog.cpp
win-linux/src/platform_linux/kdefiledialog.h
win-linux/src/utils.cpp

Added enhancement 52701: using native KDE file dialog

Added enhancement 52701: using native KDE file dialog

---

win-linux/src/components/cfiledialog.cpp

Fixed bug 46214: format filters are configured incorrectly

Fixed bug 46214: format filters are configured incorrectly

---

win-linux/src/windows/cmainwindow.cpp

Fixed bug 42806: focus on opening files

Fixed bug 42806: focus on opening files

---

win-linux/src/main.cpp
win-linux/src/utils.cpp
win-linux/src/windows/cmainwindow.cpp

Refactoring desktop environment detection on Linux

Refactoring desktop environment detection on Linux

---

win-linux/defaults.pri
win-linux/src/cascapplicationmanagerwrapper.cpp
win-linux/src/cascapplicationmanagerwrapper.h
win-linux/src/cascapplicationmanagerwrapper_private.h
win-linux/src/components/cmessage.cpp
win-linux/src/main.cpp
win-linux/src/platform_linux/singleapplication.cpp
win-linux/src/platform_linux/singleapplication.h
win-linux/src/platform_win/singleapplication.cpp
win-linux/src/platform_win/singleapplication.h
win-linux/src/windows/cwindowbase.cpp

Fixed bug 56667: prevent multiple instances on Windows

Fixed bug 56667: prevent multiple instances on Windows

---

win-linux/src/chelp.cpp
win-linux/src/components/cfiledialog.cpp
win-linux/src/components/cfiledialog.h
win-linux/src/platform_linux/xdgdesktopportal.cpp

- Adaptation xdgdesktopportal for old D-Bus versions,
- Added feature to save and reset --xdg-desktop-portal option,
- Refactoring CFileDialog.

Fixes related to xdg-desktop-portal

---

win-linux/src/windows/ceditorwindow.cpp
win-linux/src/windows/ceditorwindow_p.h
win-linux/src/windows/cmainwindow.cpp

Added enhancement 53084: display of the file name on the taskbar

Added display of the file name on the taskbar

---

win-linux/src/components/cfiledialog.cpp
win-linux/src/components/cfiledialog.h

Added enhancement 47764: added a filter for all files supported for opening

Added a filter for all files supported for opening

---

win-linux/src/windows/ceditorwindow.cpp
win-linux/src/windows/ceditorwindow_p.h

- Fixed bug 58043: prevention flicker effect

Fixed bug 58043: prevention flicker effect

---

win-linux/src/cascapplicationmanagerwrapper_private.h

Fixed inheritance of the editor window state from the main window

Fixed inheritance of the editor window state from the main window

---

win-linux/defaults.pri
win-linux/src/ceditortools.cpp
win-linux/src/components/cprintdialog.cpp
win-linux/src/components/cprintdialog.h
win-linux/src/platform_linux/gtkprintdialog.cpp
win-linux/src/platform_linux/gtkprintdialog.h
win-linux/src/windows/ceditorwindow_p.h
win-linux/src/windows/cmainwindow.cpp

- Added feature: Gtk print dialog

Added feature: Gtk print dialog

---

win-linux/package/windows/DesktopEditors.aip
win-linux/src/asctabwidget.cpp

- Fixed switching to a tab with a document open using Drag'n'Drop

Fix bug #59024: switching to a tab with a document open using Drag'n'Drop

---

win-linux/package/windows/associate_page.iss

Restore register values after uninstall program (Windows)

Restore register values after uninstall program (Windows)

---

win-linux/res/styles/tabbar@1.25x.qss
win-linux/res/styles/tabbar@1.5x.qss
win-linux/res/styles/tabbar@1.75x.qss
win-linux/res/styles/tabbar@1x.qss
win-linux/res/styles/tabbar@2x.qss
win-linux/res/styles/theme-contrast-dark.qss
win-linux/src/utils.h

- Refactoring dark-contrast theme, utils.h

Refactoring dark-contrast theme, utils.h

---

win-linux/src/ceditorwindow_p.h
win-linux/src/cmainpanel.cpp

Disable currentPage option in cells

Fix bug 59208.

---

common/loginpage/providers/onlyoffice/config.json

Opening the editor in desktop instead of a browser tab

editorPage for community server and docspace

---

win-linux/package/windows/DesktopEditors.aip
win-linux/package/windows/dictionary.ail

Fix advinst build

---

win-linux/package/linux/Makefile

* Build packages for different distributions
* Small fix

Fix develop

---

common/loginpage/providers/liferay/config.json

Confirm this plz
@DenisDeeSign

Fix liferay start page

---

win-linux/package/windows/dictionary.ail

Fix msi translations

---

win-linux/package/windows/common.iss

Fix post-update application launch

---

win-linux/package/windows/DesktopEditors.aip
win-linux/package/windows/dictionary.ail

Fix msi property localization

---

win-linux/package/windows/common.iss
win-linux/package/windows/make_zip.ps1

Fix sign dlls

---

win-linux/package/windows/common.iss
win-linux/package/windows/make_zip.ps1

Sign all DLLs

---

win-linux/src/windows/platform_win/cwindowplatform.cpp

(cherry picked from commit cf81eaacc6fcfe65fa128dc15c19f1bd00e0f3f5)

[win] fix bug 62774

---

win-linux/package/windows/common.iss
win-linux/package/windows/make_zip.ps1

- Include visual elements in zip update file
- Exclude vlc-cache-gen from zip update file

Fix bug 64472, fix bug 64509

---

common/loginpage/locale/pt-PT.js

Update pt-PT translation in login page

Update pt-PT translation

---

common/loginpage/providers/moodle/config.json

This reverts commit b0cb77c9792b91522f3dcf5f43a81476acc50310.

Revert "[start page] changed Moodle provider config"

---

macos/ONLYOFFICE/Code/Utils/ascprinter.h

Fixed print to PDF (and, presumably, via actual printer) for documents with different page orientations.
(Print preview for those kind of documents is still broken though)

Fix macos printing

---

macos/Localization/bg.xliff
macos/Localization/en.xliff
macos/Localization/es.xliff
macos/Localization/et.xliff
macos/Localization/ga.xliff
macos/Localization/hu.xliff
macos/Localization/id.xliff
macos/Localization/lt.xliff
macos/Localization/lv.xliff
macos/Localization/nl.xliff
macos/Localization/pt-BR.xliff
macos/Localization/ru.xliff
macos/Localization/sr-Cyrl-RS.xliff
macos/Localization/sr-Latn-RS.xliff
macos/Localization/tr.xliff

Fix translations for bug 63451

Fix translations
